-- Create the listings table
create table public.listings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  location text not null,
  price numeric not null,
  category text not null, -- 'apartment', 'house', 'single', etc.
  type text not null default 'rent', -- 'rent' or 'sale'
  description text,
  image_url text,
  amenities text[], -- Array of strings
  rating numeric default 0,
  reviews_count integer default 0,
  user_id uuid references auth.users not null
);

-- Enable Row Level Security (RLS) for listings
alter table public.listings enable row level security;

-- Create policies for listings
-- 1. Allow everyone to view listings
create policy "Listings are viewable by everyone"
  on public.listings for select
  using ( true );

-- 2. Allow authenticated users to insert their own listings
create policy "Users can insert their own listings"
  on public.listings for insert
  with check ( auth.uid() = user_id );

-- 3. Allow users to update their own listings
create policy "Users can update their own listings"
  on public.listings for update
  using ( auth.uid() = user_id );

-- 4. Allow users to delete their own listings
create policy "Users can delete their own listings"
  on public.listings for delete
  using ( auth.uid() = user_id );

-- --- PROFILES ---

-- Create a table for public profiles
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone,
  full_name text,
  avatar_url text,
  website text,
  role text default 'user'
);

-- Enable RLS for profiles
alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to call the function on new user creation
create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- --- STORAGE ---

-- Create a storage bucket for 'listings'
-- Note: You might need to create the bucket manually in the dashboard if this fails,
-- but the policies below are essential.

insert into storage.buckets (id, name, public)
values ('listings', 'listings', true)
on conflict (id) do nothing;

-- Policy: Allow public access to view files
create policy "Public Access"
  on storage.objects for select
  using ( bucket_id = 'listings' );

-- Policy: Allow authenticated users to upload files
create policy "Authenticated users can upload"
  on storage.objects for insert
  with check (
    bucket_id = 'listings'
    and auth.role() = 'authenticated'
  );

-- Policy: Allow users to update/delete their own files (optional, for completeness)
create policy "Users can update own files"
  on storage.objects for update
  using (
    bucket_id = 'listings'
    and auth.uid() = owner
  );

create policy "Users can delete own files"
  on storage.objects for delete
  using (
    bucket_id = 'listings'
    and auth.uid() = owner
  );
