-- Create the listings table
create table public.listings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  location text not null,
  price numeric not null,
  category text not null, -- 'apartment', 'house', 'single', etc.
  type text not null default 'rent', -- 'rent' or 'sale'
  description text,
  image_url text,
  amenities text[], -- Array of strings
  rating numeric default 0,
  reviews_count integer default 0,
  user_id uuid references auth.users not null
);

-- Enable Row Level Security (RLS) for listings
alter table public.listings enable row level security;

-- Create policies for listings
-- 1. Allow everyone to view listings
create policy "Listings are viewable by everyone"
  on public.listings for select
  using ( true );

-- 2. Allow authenticated users to insert their own listings
create policy "Users can insert their own listings"
  on public.listings for insert
  with check ( auth.uid() = user_id );

-- 3. Allow users to update their own listings
create policy "Users can update their own listings"
  on public.listings for update
  using ( auth.uid() = user_id );

-- 4. Allow users to delete their own listings
create policy "Users can delete their own listings"
  on public.listings for delete
  using ( auth.uid() = user_id );

-- --- PROFILES ---

-- Create a table for public profiles
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone,
  full_name text,
  avatar_url text,
  website text,
  role text default 'user'
);

-- Enable RLS for profiles
alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to call the function on new user creation
create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- --- STORAGE ---

-- Create a storage bucket for 'listings'
-- Note: You might need to create the bucket manually in the dashboard if this fails,
-- but the policies below are essential.

insert into storage.buckets (id, name, public)
values ('listings', 'listings', true)
on conflict (id) do nothing;

-- Policy: Allow public access to view files
create policy "Public Access"
  on storage.objects for select
  using ( bucket_id = 'listings' );

-- Policy: Allow authenticated users to upload files
create policy "Authenticated users can upload"
  on storage.objects for insert
  with check (
    bucket_id = 'listings'
    and auth.role() = 'authenticated'
  );

-- Policy: Allow users to update/delete their own files (optional, for completeness)
create policy "Users can update own files"
  on storage.objects for update
  using (
    bucket_id = 'listings'
    and auth.uid() = owner
  );

create policy "Users can delete own files"
  on storage.objects for delete
  using (
    bucket_id = 'listings'
    and auth.uid() = owner
  );

-- --- KYC VERIFICATION SYSTEM ---

-- Add verification status to profiles
alter table public.profiles 
add column if not exists is_verified boolean default false,
add column if not exists verification_badge text default null;

-- Create KYC verifications table
DROP TABLE IF EXISTS public.kyc_verifications;

CREATE TABLE public.kyc_verifications (
  user_id uuid PRIMARY KEY REFERENCES auth.users NOT NULL,
  citizenship_photo_url text,
  citizenship_number text,
  phone_number text,
  otp_code text,
  otp_expires_at timestamp with time zone,
  status text DEFAULT 'pending',
  rejection_reason text,
  submitted_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  verified_at timestamp with time zone,
  verified_by uuid REFERENCES auth.users
);

-- Enable RLS for KYC verifications
alter table public.kyc_verifications enable row level security;

-- Users can view their own KYC status
create policy "Users can view own KYC"
  on kyc_verifications for select
  using ( auth.uid() = user_id );

-- Users can insert their own KYC
create policy "Users can submit own KYC"
  on kyc_verifications for insert
  with check ( auth.uid() = user_id );

-- Users can update their own pending KYC
create policy "Users can update own pending KYC"
  on kyc_verifications for update
  using ( auth.uid() = user_id and status = 'pending' );

-- --- REPORTING SYSTEM ---

-- Create reports table
create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  listing_id bigint references public.listings on delete cascade not null,
  reporter_id uuid references auth.users not null,
  reason text not null, -- 'fake_listing', 'scam', 'inappropriate', 'doesnt_exist', 'unresponsive'
  details text,
  status text default 'pending', -- 'pending', 'resolved', 'dismissed'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  resolved_at timestamp with time zone,
  resolved_by uuid references auth.users,
  resolution_notes text
);

-- Enable RLS for reports
alter table public.reports enable row level security;

-- Users can view their own reports
create policy "Users can view own reports"
  on reports for select
  using ( auth.uid() = reporter_id );

-- Authenticated users can create reports
create policy "Authenticated users can report"
  on reports for insert
  with check ( auth.role() = 'authenticated' );

-- Create storage bucket for KYC documents
insert into storage.buckets (id, name, public)
values ('kyc-documents', 'kyc-documents', false)
on conflict (id) do nothing;

-- Policy: Allow authenticated users to upload their KYC documents
create policy "Users can upload own KYC documents"
  on storage.objects for insert
  with check (
    bucket_id = 'kyc-documents'
    and auth.role() = 'authenticated'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

-- Policy: Users can view their own KYC documents
create policy "Users can view own KYC documents"
  on storage.objects for select
  using (
    bucket_id = 'kyc-documents'
    and (storage.foldername(name))[1] = auth.uid()::text
  );
