-- Create KYC verifications table
create table if not exists public.kyc_verifications (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null unique,
  citizenship_photo_url text,
  citizenship_number text,
  phone_number text,
  otp_code text,
  otp_expires_at timestamp with time zone,
  status text default 'pending', -- 'pending', 'approved', 'rejected'
  rejection_reason text,
  submitted_at timestamp with time zone default timezone('utc'::text, now()) not null,
  verified_at timestamp with time zone,
  verified_by uuid references auth.users
);

-- Enable RLS for KYC verifications
alter table public.kyc_verifications enable row level security;

-- Users can view their own KYC status
create policy "Users can view own KYC"
  on kyc_verifications for select
  using ( auth.uid() = user_id );

-- Users can insert their own KYC
create policy "Users can submit own KYC"
  on kyc_verifications for insert
  with check ( auth.uid() = user_id );

-- Users can update their own pending KYC
create policy "Users can update own pending KYC"
  on kyc_verifications for update
  using ( auth.uid() = user_id and status = 'pending' );

-- Create reports table (also likely missing)
create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  listing_id bigint references public.listings on delete cascade not null,
  reporter_id uuid references auth.users not null,
  reason text not null, -- 'fake_listing', 'scam', 'inappropriate', 'doesnt_exist', 'unresponsive'
  details text,
  status text default 'pending', -- 'pending', 'resolved', 'dismissed'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  resolved_at timestamp with time zone,
  resolved_by uuid references auth.users,
  resolution_notes text
);

-- Enable RLS for reports
alter table public.reports enable row level security;

-- Users can view their own reports
create policy "Users can view own reports"
  on reports for select
  using ( auth.uid() = reporter_id );

-- Authenticated users can create reports
create policy "Authenticated users can report"
  on reports for insert
  with check ( auth.role() = 'authenticated' );
