-- Create the listings table
create table public.listings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  location text not null,
  price numeric not null,
  category text not null, -- 'apartment', 'house', 'single', etc.
  type text not null default 'rent', -- 'rent' or 'sale'
  description text,
  image_url text,
  amenities text[], -- Array of strings
  rating numeric default 0,
  reviews_count integer default 0,
  -- ARCHIVED: removed content (merged into ../combined_migration.sql)
    and auth.role() = 'authenticated'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

-- Policy: Users can view their own KYC documents
create policy "Users can view own KYC documents"
  on storage.objects for select
  using (
    bucket_id = 'kyc-documents'
    and (storage.foldername(name))[1] = auth.uid()::text
  );
