-- ==========================================
-- KHOZNA.com COMPLETE DATABASE SETUP
-- ==========================================
-- Copy ALL of this and run it in the Supabase SQL Editor
-- This will create the missing tables and storage buckets.
-- ==========================================

-- 1. Create KYC Verifications Table
create table if not exists public.kyc_verifications (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null unique,
  citizenship_photo_url text,
  citizenship_number text,
  phone_number text,
  otp_code text,
  otp_expires_at timestamp with time zone,
  status text default 'pending', -- 'pending', 'approved', 'rejected'
  rejection_reason text,
  submitted_at timestamp with time zone default timezone('utc'::text, now()) not null,
  verified_at timestamp with time zone,
  verified_by uuid references auth.users
);

-- 2. Enable Security for KYC
alter table public.kyc_verifications enable row level security;

create policy "Users can view own KYC"
  on kyc_verifications for select
  using ( auth.uid() = user_id );

create policy "Users can submit own KYC"
  on kyc_verifications for insert
  with check ( auth.uid() = user_id );

create policy "Users can update own pending KYC"
  on kyc_verifications for update
  using ( auth.uid() = user_id and status = 'pending' );

-- 3. Create Reports Table
create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  listing_id bigint references public.listings on delete cascade not null,
  reporter_id uuid references auth.users not null,
  reason text not null,
  details text,
  status text default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  resolved_at timestamp with time zone,
  resolved_by uuid references auth.users,
  resolution_notes text
);

-- 4. Enable Security for Reports
alter table public.reports enable row level security;

create policy "Users can view own reports"
  on reports for select
  using ( auth.uid() = reporter_id );

create policy "Authenticated users can report"
  on reports for insert
  with check ( auth.role() = 'authenticated' );

-- 5. Create Storage Bucket for KYC
insert into storage.buckets (id, name, public)
values ('kyc-documents', 'kyc-documents', false)
on conflict (id) do nothing;

-- 6. Enable Security for Storage
create policy "Users can upload own KYC documents"
  on storage.objects for insert
  with check (
    bucket_id = 'kyc-documents'
    and auth.role() = 'authenticated'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "Users can view own KYC documents"
  on storage.objects for select
  using (
    bucket_id = 'kyc-documents'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

-- ==========================================
-- SETUP COMPLETE
-- ==========================================
