-- Create notifications table
CREATE TABLE IF NOT EXISTS public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  message text not null,
  type text not null default 'info', -- 'info', 'success', 'warning', 'error'
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- Users can view their own notifications
CREATE POLICY "Users can view own notifications"
  ON notifications FOR SELECT
  USING ( auth.uid() = user_id );

-- Users can update their own notifications (mark as read)
CREATE POLICY "Users can update own notifications"
  ON notifications FOR UPDATE
  USING ( auth.uid() = user_id );

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS notifications_user_id_idx ON notifications(user_id);
CREATE INDEX IF NOT EXISTS notifications_is_read_idx ON notifications(is_read);
